// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQf5sZS9Ve66qubyDbGs0PcJ6awp3VM0U',
    appId: '1:850789059915:web:d1dc9e730a9b1e8d76ecce',
    messagingSenderId: '850789059915',
    projectId: 'limitless-iot-17e8f',
    authDomain: 'limitless-iot-17e8f.firebaseapp.com',
    storageBucket: 'limitless-iot-17e8f.firebasestorage.app',
    measurementId: 'G-C80CFCL8DH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_yKE7Dik3G4bk3jGbBgACYY8urkiq27o',
    appId: '1:850789059915:android:ea4c5eeea7c27ca276ecce',
    messagingSenderId: '850789059915',
    projectId: 'limitless-iot-17e8f',
    storageBucket: 'limitless-iot-17e8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpW_8lOojcS1W79pMtAUWjCVjGvMi1a6U',
    appId: '1:615271668557:ios:76e2663e52f0f7f1f2f504',
    messagingSenderId: '615271668557',
    projectId: 'geofence-23924',
    storageBucket: 'geofence-23924.firebasestorage.app',
    iosBundleId: 'com.example.geofence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADykx581l-LZkYgZP1OB7uryD3Pq9U7ow',
    appId: '1:974321856114:web:3940912be3e5c7bc531ceb',
    messagingSenderId: '974321856114',
    projectId: 'limitless-iot',
    authDomain: 'limitless-iot.firebaseapp.com',
    storageBucket: 'limitless-iot.firebasestorage.app',
    measurementId: 'G-ZB73RCNPYG',
  );

}