// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADykx581l-LZkYgZP1OB7uryD3Pq9U7ow',
    appId: '1:974321856114:web:a2c85995e56169ad531ceb',
    messagingSenderId: '974321856114',
    projectId: 'limitless-iot',
    authDomain: 'limitless-iot.firebaseapp.com',
    storageBucket: 'limitless-iot.firebasestorage.app',
    measurementId: 'G-MBCPLLRD6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh3cuszLYtdp2GxYIscJOUj8-bFkqEzSA',
    appId: '1:974321856114:android:bee3f2311d6702e1531ceb',
    messagingSenderId: '974321856114',
    projectId: 'limitless-iot',
    storageBucket: 'limitless-iot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpW_8lOojcS1W79pMtAUWjCVjGvMi1a6U',
    appId: '1:615271668557:ios:76e2663e52f0f7f1f2f504',
    messagingSenderId: '615271668557',
    projectId: 'geofence-23924',
    storageBucket: 'geofence-23924.firebasestorage.app',
    iosBundleId: 'com.example.geofence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADykx581l-LZkYgZP1OB7uryD3Pq9U7ow',
    appId: '1:974321856114:web:3940912be3e5c7bc531ceb',
    messagingSenderId: '974321856114',
    projectId: 'limitless-iot',
    authDomain: 'limitless-iot.firebaseapp.com',
    storageBucket: 'limitless-iot.firebasestorage.app',
    measurementId: 'G-ZB73RCNPYG',
  );

}