// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg4Zb2e1soq74wYV2dv7YN8RlxrMsPFhw',
    appId: '1:615271668557:web:2e9304293638ccddf2f504',
    messagingSenderId: '615271668557',
    projectId: 'geofence-23924',
    authDomain: 'geofence-23924.firebaseapp.com',
    storageBucket: 'geofence-23924.firebasestorage.app',
    measurementId: 'G-Q6C84ES7QG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0YJm6nBZvOZ5kOn9Mlaa2eKuXh2dlFOs',
    appId: '1:615271668557:android:e934e35a4392e85ff2f504',
    messagingSenderId: '615271668557',
    projectId: 'geofence-23924',
    storageBucket: 'geofence-23924.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpW_8lOojcS1W79pMtAUWjCVjGvMi1a6U',
    appId: '1:615271668557:ios:76e2663e52f0f7f1f2f504',
    messagingSenderId: '615271668557',
    projectId: 'geofence-23924',
    storageBucket: 'geofence-23924.firebasestorage.app',
    iosBundleId: 'com.example.geofence',
  );
}
