import 'dart:io';

/// Increments BUILD_NUMBER and regenerates lib/app_version.g.dart
/// so the drawer version auto-updates on each rebuild/launch.
void main() {
  const prefix = 'V1.0';
  final root = Directory.current;
  final buildFile = File('${root.path}${Platform.pathSeparator}BUILD_NUMBER');
  final outFile = File(
    '${root.path}${Platform.pathSeparator}lib${Platform.pathSeparator}app_version.g.dart',
  );

  var build = 1;
  if (buildFile.existsSync()) {
    build = (int.tryParse(buildFile.readAsStringSync().trim()) ?? 0) + 1;
  }
  buildFile.writeAsStringSync('$build\n');

  final version = '$prefix.$build';
  outFile.writeAsStringSync('''
// Generated by tool/bump_version.dart - do not edit by hand.
// ignore_for_file: constant_identifier_names

const String APP_VERSION = '$version';
const int APP_BUILD = $build;
''');

  stdout.writeln('App version: $version');
}
